---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-4k
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sonarr-4k-secret
    creationPolicy: Owner
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr-4k
