---
apiVersion: v1
kind: Pod
metadata:
  name: test-pvc
  namespace: media
spec:
  containers:
    - name: test-pod
      image: ubuntu
      command:
        [
          "/bin/bash",
          "-c",
          " apt update && apt install -y gnupg lsb-release wget && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && echo \"deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main\" > /etc/apt/sources.list.d/pgdg.list && apt update && apt install -y rsync tmux nano pgloader sqlite3 python3 postgresql-client-17 && sleep 3600",
        ]
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /backups
          name: backups
      resources:
        limits:
          memory: 2Gi
          cpu: "500m"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: radarr
    - name: backups
      nfs:
        server: granite.markmckessock.com
        path: /volume1/Backups
        readOnly: true
  restartPolicy: Never
