---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: splitflap-webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: splitflap-webhook-secret
    creationPolicy: Owner
    template:
      data:
        TWILIO_AUTH_TOKEN: "{{ .TWILIO_AUTH_TOKEN }}"
        TWILIO_WEBHOOK_URL: "{{ .TWILIO_WEBHOOK_URL }}"
  dataFrom:
    - extract:
        key: splitflap-webhook
