---
apiVersion: v1
kind: ConfigMap
metadata:
  name: photoframe-webhook-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: photoframe-webhook
        group: home-automation
        url: http://photoframe-webhook.home-automation.svc.cluster.local:5000/healthz
        interval: 1m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
